In [16]:
import numpy as np
import torch
a = np.array([[1,4,7],[2,5,8],[3,6,9]])
A = np.matrix(a)
c = np.array([1,5,9])
C = np.matrix(c)
print(C.transpose())
print(A)
print(np.linalg.pinv(a))
print(np.dot(np.linalg.pinv(a),C.transpose()))

for i in range(10,0,-1):
    pass
print(i)
H1 = np.random.rand(*a.shape) < 0.5
a *= H1 
print(a)
H2 = torch.randn(a.shape) < 0.5
max = [0,1,2]
for ly in range(1,5):
    if ly in max:
        print("max")
print(H2)
w = 2**3


[[1]
 [5]
 [9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[-6.38888889e-01 -5.55555556e-02  5.27777778e-01]
 [-1.66666667e-01  6.55053106e-17  1.66666667e-01]
 [ 3.05555556e-01  5.55555556e-02 -1.94444444e-01]]
[[ 3.83333333]
 [ 1.33333333]
 [-1.16666667]]
1
[[1 4 0]
 [0 0 8]
 [3 0 0]]
max
max
tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False,  True,  True]])


In [5]:


# 假设有一个 seq_len=4 的输入序列
seq_len = 3

# 创建 lookahead mask (upper triangular matrix)
mask = torch.triu(torch.ones(2,seq_len, seq_len), diagonal=1)  # (seq_len, seq_len)
mask = mask == 1  # 将上三角部分设为 True，其他部分为 False
print(mask)


tensor([[[False,  True,  True],
         [False, False,  True],
         [False, False, False]],

        [[False,  True,  True],
         [False, False,  True],
         [False, False, False]]])


In [6]:
x = torch.randn((2,10,4))

y = torch.randn((2,10000,5000))
y = torch.transpose(y,1,2)


In [12]:
class MyModule(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.linears = torch.nn.ModuleList([torch.nn.Linear(10, 10) for i in range(2)])

    def forward(self, x):
        # ModuleList can act as an iterable, or be indexed using ints
        for i, l in enumerate(self.linears):
            x = self.linears[i // 2](x) + l(x)
        return x
myModule = MyModule()
print(myModule)


MyModule(
  (linears): ModuleList(
    (0-1): 2 x Linear(in_features=10, out_features=10, bias=True)
  )
)


In [7]:
# 简单测试 LayerNorm
out = torch.tensor([[[-1.6404, -0.5955,  0.4495,  1.4945],
         [-1.4424, -0.4172,  0.6081,  1.6333],
         [-1.2530, -0.2450,  0.7630,  1.7710],
         [-1.0743, -0.0805,  0.9133,  1.9071]],

        [[ 0.1337,  0.8191,  1.5044,  2.1897],
         [ 0.2926,  0.9694,  1.6462,  2.3230],
         [ 0.4441,  1.1145,  1.7848,  2.4552],
         [ 0.5900,  1.2555,  1.9211,  2.5866]]])
print(out.mean(dim=-1,keepdim=True))
print(out.std(dim=-1,keepdim=True))
out1 = torch.tensor([[[-1.2404, -0.2277,  0.7850,  1.7977],
         [-1.1715, -0.1785,  0.8145,  1.8075],
         [-1.1110, -0.1353,  0.8404,  1.8161],
         [-1.0614, -0.0998,  0.8617,  1.8232]],

        [[ 0.0176,  0.6707,  1.3237,  1.9768],
         [ 0.0474,  0.6920,  1.3365,  1.9811],
         [ 0.0699,  0.7080,  1.3461,  1.9842],
         [ 0.0867,  0.7200,  1.3533,  1.9866]]])
print(out1.mean(dim=-1,keepdim=True))
print(out1.std(dim=-1,keepdim=True))
print((out1-out1.mean(dim=-1,keepdim=True))/out1.std(dim=-1,keepdim=True))
layer_norm = torch.nn.LayerNorm(4)  # 假设 emb_dim=4
output = layer_norm(x)
print("LayerNorm Output:", output)
print(output.std(dim=-1,keepdim=True))


tensor([[[-0.0730],
         [ 0.0955],
         [ 0.2590],
         [ 0.4164]],

        [[ 1.1617],
         [ 1.3078],
         [ 1.4497],
         [ 1.5883]]])
tensor([[[1.3491],
         [1.3236],
         [1.3013],
         [1.2830]],

        [[0.8848],
         [0.8737],
         [0.8654],
         [0.8592]]])
tensor([[[0.2787],
         [0.3180],
         [0.3525],
         [0.3809]],

        [[0.9972],
         [1.0143],
         [1.0271],
         [1.0367]]])
tensor([[[1.3074],
         [1.2820],
         [1.2596],
         [1.2413]],

        [[0.8431],
         [0.8321],
         [0.8238],
         [0.8176]]])
tensor([[[-1.1619, -0.3873,  0.3873,  1.1619],
         [-1.1619, -0.3873,  0.3873,  1.1619],
         [-1.1619, -0.3873,  0.3873,  1.1619],
         [-1.1619, -0.3873,  0.3873,  1.1619]],

        [[-1.1619, -0.3873,  0.3873,  1.1619],
         [-1.1619, -0.3873,  0.3873,  1.1619],
         [-1.1619, -0.3873,  0.3873,  1.1619],
         [-1.1619, -0.3873,  0.3873, 

In [ ]:
"""
    #x_ = torch.transpose(x,2,1)
    #        out1 = self.Mutiheads(x,x,x)
     #       #x_clone = x
      #      #print(x + out1)
       #     #print("out1:\n",out1)
        #    #out1 = self.Mutiheads(x,x,x)
         #   #print("Input to LayerNorm - Mean:\n",(x_clone+ out1).mean(dim=-1))
         #   #print("Input to LayerNorm - Std:\n",(x_clone+ out1).std(dim=-1))
         #   out2 = self.Layernorm1(out1 + x)
         #   out2 = self.dropout(out2)
          #  #out2 = self.Layernorm1(out2 + x_clone)
            #print("(Layernorm)out2:\n",out2)
          #  out3 = self.feedforward(out2)
            #print("out3:\n",out3)
            #out = self.dropout1(out3)
           # out = self.Layernorm2(out2+out3)
            #y = self.dropout(out)
            #y = out
            self.mlps = nn.ModuleList([
            nn.Linear(inp_dim, hidden_dim_feedforward),  # First MLP layer
            nn.ReLU(),                                  # ReLU activation
            nn.Linear(hidden_dim_feedforward, inp_dim)   # Second MLP layer
        ])
        for mlp in self.mlps:
            if isinstance(mlp, nn.Linear):  # Check if the module is a Linear layer
                nn.init.xavier_normal_(mlp.weight)  # Xavier initialization for weights
            """

In [13]:
import torch
import torch.nn as nn

dropout = nn.Dropout(p=0.5)  # 50% dropout rate
x = torch.ones(5)

# 模拟两次 Dropout
y1 = dropout(x)  # 第一次 Dropout
y2 = dropout(x)  # 第二次 Dropout

print(y1)
print(y2)
print(x)

tensor([0., 0., 2., 2., 2.])
tensor([2., 2., 2., 2., 0.])
tensor([1., 1., 1., 1., 1.])


In [ ]:
import torch.nn.functional as F

mask = (torch.rand_like(x) > 0.5).float() / 0.5  # 生成 Dropout 掩码
y1 = x * mask  # 应用相同的 Dropout 掩码
y2 = x * mask  # 再次应用相同的 Dropout 掩码
dropout_ = F.dropout(x,0.2)
dropout_1 = F.dropout(x,0.2)
print(dropout_)
print(dropout_1)


tensor([1.6667, 1.6667, 1.6667, 1.6667, 1.6667])
tensor([0.0000, 1.6667, 1.6667, 1.6667, 1.6667])


In [23]:
a = torch.zeros((3))
div_term = torch.pow(10000,-a)
position = torch.arange(5).unsqueeze(1)
print(torch.cos(position * div_term))
print(div_term)

tensor([[ 1.0000,  1.0000,  1.0000],
        [ 0.5403,  0.5403,  0.5403],
        [-0.4161, -0.4161, -0.4161],
        [-0.9900, -0.9900, -0.9900],
        [-0.6536, -0.6536, -0.6536]])
tensor([1., 1., 1.])
